// M36: glyphs — 1:1 from spec §6, fancy + legacy pairs.
import { describe, expect, it } from "vitest"
import { GLYPHS, makeGlyphs } from "../src/glyphs/index.ts"

describe("makeGlyphs(true)", () => {
  it("returns the fancy set (spec §6)", () => {
    const g = makeGlyphs(true)
    expect(g.promptArrow).toBe("❯ ")
    expect(g.recordDotFilled).toBe("◉")
    expect(g.recordDotEmpty).toBe("◎")
    expect(g.collapsedAccent).toBe("❙")
    expect(g.ballotX).toBe("✗")
    expect(g.checkMark).toBe("✓")
    expect(g.enlarge).toBe("↗")
    expect(g.copyIcon).toBe("⧉")
    expect(g.tokenArrow).toBe("⇣")
    expect(g.monitorFrames).toEqual(["○", "◎", "◉", "◎"])
    expect(g.diamonds).toEqual(["◆", "◇", "◈"])
    expect(g.accentBar).toBe("┃")
    expect(g.timelineUp).toBe("▴")
    expect(g.timelineDown).toBe("▾")
    expect(g.timelineBold).toBe("━━")
    expect(g.timelineThin).toBe("──")
    expect(g.filledDot).toBe("●")
    expect(g.selectionBar).toBe("▏")
    expect(g.chevronRight).toBe("›")
    expect(g.chevronLeft).toBe("‹")
    expect(g.chevronDown).toBe("⌄")
    expect(g.disclosureOpen).toBe("▾")
    expect(g.disclosureClosed).toBe("▸")
    expect(g.buttonClose).toBe("[✗]")
    expect(g.buttonEnlarge).toBe("[↗]")
    expect(g.brailleSpinner).toEqual(["⠋", "⠙", "⠹", "⠸", "⠼", "⠴", "⠦", "⠧"])
    expect(g.dotSpinner).toEqual(["⋅", " :", "⸬", "⁙"])
    expect(g.progressBlocks).toEqual(["▏", "▎", "▍", "▌", "▋", "▊", "▉", "█"])
    expect(g.todoPending).toBe("□")
    expect(g.todoInProgress).toBe("▶")
    expect(g.todoDone).toBe("✓")
    expect(g.todoCancelled).toBe("✗")
  })
})

describe("makeGlyphs(false)", () => {
  it("returns the legacy fallbacks (exact pairs)", () => {
    const l = makeGlyphs(false)
    expect(l.promptArrow).toBe("> ")
    expect(l.recordDotFilled).toBe("*")
    expect(l.recordDotEmpty).toBe("o")
    expect(l.collapsedAccent).toBe("|")
    expect(l.ballotX).toBe("x")
    expect(l.checkMark).toBe("√")
    expect(l.enlarge).toBe("o")
    expect(l.copyIcon).toBe("c")
    expect(l.tokenArrow).toBe("↓")
    expect(l.monitorFrames).toEqual(["·", "○", "•", "○"])
    expect(l.diamonds).toEqual(["♦", "○", "♦"])
    expect(l.accentBar).toBe("│")
    expect(l.timelineUp).toBe("▲")
    expect(l.timelineDown).toBe("▼")
    expect(l.timelineBold).toBe("══")
    expect(l.timelineThin).toBe("─")
    expect(l.filledDot).toBe("•")
    expect(l.selectionBar).toBe("│")
    expect(l.chevronRight).toBe(">")
    expect(l.chevronLeft).toBe("<")
    expect(l.chevronDown).toBe("v")
    expect(l.disclosureOpen).toBe("v")
    expect(l.disclosureClosed).toBe(">")
    expect(l.buttonClose).toBe("[x]")
    expect(l.buttonEnlarge).toBe("[o]")
    expect(l.brailleSpinner).toEqual(["|", "/", "-", "\\"])
    expect(l.dotSpinner).toEqual([" ", ".", "·", ":"])
    expect(l.progressBlocks).toEqual(["▏", "▎", "▍", "▌", "▋", "▊", "▉", "█"])
    expect(l.todoPending).toBe("□")
    expect(l.todoInProgress).toBe("▶")
    expect(l.todoDone).toBe("✓")
    expect(l.todoCancelled).toBe("✗")
  })
})

describe("GLYPHS", () => {
  it("is the frozen fancy default", () => {
    expect(Object.isFrozen(GLYPHS)).toBe(true)
    expect(GLYPHS.promptArrow).toBe("❯ ")
    expect(Object.isFrozen(GLYPHS.monitorFrames)).toBe(true)
    expect(Object.isFrozen(GLYPHS.brailleSpinner)).toBe(true)
    expect(GLYPHS.brailleSpinner).toHaveLength(8)
  })
})
